In [1]:
import os
import pickle
import random

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt

from torch.utils.data import DataLoader

from kumaraswamy import Kumaraswamy
from hard_kumaraswamy import StretchedAndRectifiedDistribution as HardKumaraswamy

In [2]:
a = torch.tensor([0.0708])
b = torch.tensor([3.5888])

kuma = Kumaraswamy(a, b)

m = HardKumaraswamy(kuma)

print(m.log_prob(torch.tensor([.99])))

print(m.stretched.cdf(torch.tensor([1.])))

tensor([1.0000])
tensor([nan])
tensor([nan])
tensor([-14.3855])
tensor([1.0000])


In [55]:
EPS = 1e-5

a = torch.tensor([1.])
a = torch.clamp(a, max=1.-EPS)

print(1. - EPS)
print(a)

print("-----")


b = torch.tensor([0.])
b = torch.clamp(b, min=EPS)


print(EPS)
print(b)

0.99999
tensor([1.0000])
-----
1e-05
tensor([1.0000e-05])


In [10]:
val = -m.stretched.cdf(torch.tensor([1.])) + 1 + 1e-5
# print(m.stretched.cdf(torch.tensor([1.])))
# print(1e-5)

print( 1. - m.stretched.cdf(torch.tensor([1.])))

if m.stretched.cdf(torch.tensor([1.])) > 1.:
    print("hello")

print( )

# print(val)


tensor([-1.0014e-05])
hello



In [ ]:
# a = torch.rand(3,2)
# b = torch.rand(3,2)

a = torch.tensor([0.139])
b = torch.tensor([0.286])

# kuma_prior = Kumaraswamy(torch.zeros_like(a), torch.zeros_like(b))
kuma_prior = Kumaraswamy(a, b)
kuma_post  = Kumaraswamy(a, b)

print(kuma_prior.sample())
# print(kuma_post.sample())

# print(kuma_prior.log_prob(kuma_prior.sample()))

kl_divs = []

for i in range(100):
    kl_div = torch.distributions.kl.kl_divergence(kuma_post, kuma_prior)
    kl_divs.append(kl_div)

kl_divs = torch.tensor(kl_divs)
print('KL Divergence: {}'.format(torch.mean(kl_div)))

In [ ]:
# a = torch.tensor([.0005])
# b = torch.tensor([.225])

a = torch.tensor([7.0860e-02])
b = torch.tensor([3.5888e+00])

kuma = Kumaraswamy(a, b)

m = HardKumaraswamy(kuma)

print(m.log_prob(torch.tensor([.99])))

samples = [m.sample() for _ in range(1000)]

n, bins, _ = plt.hist(samples, density=False, bins=50, weights=np.ones(len(samples)) / len(samples))
plt.grid()
plt.show()

In [ ]:
# a = torch.tensor([0.139])
# b = torch.tensor([0.286])

a = torch.tensor([.0005])
b = torch.tensor([.225])

kuma   = Kumaraswamy(a, b)
h_kuma = HardKumaraswamy(kuma)
start  = 0.

print(' val  -log_prob    prob')

for i in range(11):
    l_prob = h_kuma.log_prob(torch.tensor(start))
    print('{:.2f}    {:.4f}    {:.4f}'.format(start, -l_prob.item(), torch.exp(l_prob).item()))
    start += 0.1

In [ ]:
norm_a = torch.distributions.Normal(loc=0.0, scale=1.0)

In [ ]:
torch.exp(norm_a.log_prob(torch.tensor(0.0)))

In [ ]:
a = torch.tensor([.0])
b = torch.tensor([.0])

kuma = Kumaraswamy(a, b)

m = HardKumaraswamy(kuma)
samples = [m.sample() for _ in range(1000)]

n, bins, _ = plt.hist(samples, density=False, bins=30, weights=np.ones(len(samples)) / len(samples))