In [74]:
import os
import pickle
import random

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt

from torch.utils.data import DataLoader

from kumaraswamy import Kumaraswamy

In [81]:
a = torch.rand(3,2)
b = torch.rand(3,2)

# print(a)
# print(b)

# kuma_prior = Kumaraswamy(torch.zeros_like(a), torch.zeros_like(b))
kuma_prior = Kumaraswamy(a, b)
kuma_post  = Kumaraswamy(a, b)

print(kuma_prior.sample())
# print(kuma_post.sample())

print(kuma_prior.log_prob(kuma_prior.sample()))


kl_div = torch.distributions.kl.kl_divergence(kuma_post, kuma_prior)
print('KL Divergence: {}'.format(torch.sum(kl_div)))
print(kl_div)

tensor([[0.9826, 0.2640],
        [0.2844, 0.4427],
        [0.9443, 0.7651]])
tensor([[-1.2289,  0.0897],
        [ 7.3022, -0.2697],
        [ 1.3721, -0.0108]])
KL Divergence: 1.2195963859558105
tensor([[-2.6735,  0.5000],
        [ 0.5016, -0.1759],
        [ 2.9206,  0.1468]])


In [79]:
loc = torch.rand(3,2)
var = torch.rand(3,2)

norm_a = torch.distributions.normal.Normal(loc, var)
norm_b = torch.distributions.normal.Normal(loc, var)

# kl_div = torch.distributions.kl.kl_divergence(norm_a, norm_b)

# print(kl_div)


print(norm_a.log_prob(norm_a.sample()))




tensor([[-0.1195, -0.7692],
        [-0.5274,  0.6126],
        [ 4.7062, -0.6842]])


In [62]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])